# Site settings
title: Rizwan Ye | Honours In AI And Data Analytics 
description: Rizwan Ye's peronsal website, including his programming experiences, education, projects, and more.
url: "www.rizzwan.com" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog
google_site_verification: EDFYnxVvHGOjSYhJskFdKHTcVQJ5iTG6mqAI-grp1t0

# User settings
username: Rizwan Ye
email: test@gmail.com

# Global settings
icon_size: 58

# Google analytics tracking ID
#google_analytics_tracking_id: 
