# Site settings
title: Rizwan Ye
description: My personal programming website, including my programming experiences, education, past jobs, contact details, and more.
url: "https://rizwanye.github.io/" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Rizwan Ye
email: test@gmail.com

# Global settings
icon_size: 58

# Google analytics tracking ID
#google_analytics_tracking_id: 
